# Generated by Django 6.1 on 2026-08-16 17:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_userwishlist'),
        ('product', '0003_remove_product_product_thumb_productgallery'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Coupon code, e.g. SAVE25', max_length=50, unique=True)),
                ('discount_percentage', models.PositiveIntegerField(default=25, help_text='Percentage discount, e.g. 25 for 25%')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(help_text='Product this coupon applies to', on_delete=django.db.models.deletion.CASCADE, related_name='coupons', to='product.product')),
            ],
        ),
    ]
