# Generated by Django 6.1 on 2026-08-16 18:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_coupon'),
        ('product', '0003_remove_product_product_thumb_productgallery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='product',
            field=models.ForeignKey(blank=True, help_text='Product this coupon applies to (leave empty for storewide discount)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='coupons', to='product.product'),
        ),
    ]
