# Generated by Django 5.1.3 on 2024-12-03 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productcategory',
            name='category_name',
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='product_category',
            field=models.CharField(choices=[('meats', 'meats'), ('fruits', 'fruits'), ('vegetables', 'vegetables'), ('drinks', 'drinks'), ('others', 'others')], max_length=10),
        ),
    ]
