# Generated by Django 5.1.3 on 2024-12-07 15:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_remove_productcategory_category_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='product_thumb',
        ),
        migrations.CreateModel(
            name='ProductGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gallery', models.ImageField(blank=True, null=True, upload_to='product/thumbnails')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.product', verbose_name='Product')),
            ],
            options={
                'verbose_name': 'Product Thumbnail',
                'verbose_name_plural': 'Product Thumbnails',
            },
        ),
    ]
