# Generated by Django 5.1.3 on 2024-12-30 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogcategory',
            options={'verbose_name_plural': 'Blog Categories'},
        ),
        migrations.AddField(
            model_name='blogmodel',
            name='blog_thumb',
            field=models.ImageField(blank=True, null=True, upload_to='blog/thumbnails'),
        ),
    ]
