# Generated by Django 5.1.3 on 2025-01-30 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_blogcommentmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BlogCommentModel',
        ),
    ]
