# Generated by Django 5.1.3 on 2025-01-31 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_blogcommentmodel_count_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogcommentmodel',
            name='count_comment',
        ),
    ]
