# Generated by Django 5.1.3 on 2025-01-31 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_alter_blogcommentmodel_comment_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogcommentmodel',
            name='comment_count',
        ),
    ]
