# Generated by Django 5.1.3 on 2025-01-31 06:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_remove_blogcommentmodel_comment_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogcommentcounter',
            name='comment',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='blog.blogcommentmodel'),
            preserve_default=False,
        ),
    ]
