# Generated by Django 5.1.3 on 2025-01-31 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_blogcommentcounter_comment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BlogCommentCounter',
        ),
    ]
