# Generated by Django 5.1.3 on 2025-02-01 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0022_blogcommenttracker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogcommenttracker',
            name='comment_count',
            field=models.IntegerField(),
        ),
    ]
