# Generated by Django 5.1.3 on 2025-02-01 07:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0024_alter_blogcommenttracker_blog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogcommenttracker',
            name='blog',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.blogmodel'),
        ),
    ]
