# Generated by Django 6.1 on 2026-08-16 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_useraccount_groups_useraccount_is_superuser_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='role',
            field=models.CharField(choices=[('user', 'User'), ('member', 'Member'), ('admin', 'Admin')], default='user', max_length=10),
        ),
    ]
