# Generated by Django 5.1.3 on 2025-01-02 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_blogmodel_blog_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogmodel',
            name='blog_body',
            field=models.TextField(),
        ),
    ]
