# Generated by Django 5.1.3 on 2025-01-31 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_blogcommentmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogcommentmodel',
            name='count_comment',
            field=models.IntegerField(default=0),
        ),
    ]
