# Generated by Django 5.1.3 on 2025-01-31 06:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_remove_blogcommentmodel_count_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogCommentCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='blogcommentmodel',
            name='comment_count',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='blog.blogcommentcounter'),
            preserve_default=False,
        ),
    ]
