# Generated by Django 5.1.3 on 2025-01-31 06:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_blogcommentcounter_blogcommentmodel_comment_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogcommentmodel',
            name='comment_count',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.blogcommentcounter'),
        ),
    ]
