# Generated by Django 5.1.3 on 2025-01-31 09:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_delete_blogcommentcounter'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentOnBlogCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=0)),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.blogcommentmodel')),
            ],
        ),
    ]
