# Generated by Django 5.1.3 on 2025-01-31 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_commentonblogcount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commentonblogcount',
            old_name='blog',
            new_name='comment',
        ),
        migrations.AlterField(
            model_name='commentonblogcount',
            name='count',
            field=models.IntegerField(),
        ),
    ]
