# Generated by Django 5.1.3 on 2025-01-31 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_rename_blog_commentonblogcount_comment_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CommentOnBlogCount',
        ),
    ]
