# Generated by Django 5.1.3 on 2025-01-31 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0019_delete_commentonblogcount'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogcommentmodel',
            name='count',
            field=models.IntegerField(default=0),
        ),
    ]
