# Generated by Django 6.1 on 2026-08-17 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasehistory',
            name='payment_status',
            field=models.CharField(default='Completed', max_length=50),
        ),
        migrations.AddField(
            model_name='purchasehistory',
            name='price',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='purchasehistory',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
